### ISSUE TITLE
Problems to get work in Raspbian

### ISSUE THREAD

**Issue by x11tete11x** [gaboelnuevo/mylaunchpad#3]
hi, im trying to use it in raspbian (right now im trying from a VNC session) and get this:

pi@raspberrypi ~ $ mylaunchpad
Xlib:  extension "RANDR" missing on display ":0".
Hidden imported:  set([])
Favorites imported:  set([])
Compositing False
/usr/local/bin/mylaunchpad:272: Warning: Attempt to add property GtkSettings::gtk-button-images after class was initialised
  button = gtk.Button(" All ")
/usr/local/bin/mylaunchpad:272: Warning: Attempt to add property GtkSettings::gtk-label-select-on-focus after class was initialised
  button = gtk.Button(" All ")
/usr/local/bin/mylaunchpad:318: Warning: Attempt to add property GtkSettings::gtk-entry-select-on-focus after class was initialised
  self.search = gtk.Entry()
/usr/local/bin/mylaunchpad:318: Warning: Attempt to add property GtkSettings::gtk-entry-password-hint-timeout after class was initialised
  self.search = gtk.Entry()
Traceback (most recent call last):
  File "/usr/local/bin/mylaunchpad", line 803, in <module>
    launcher = MyLauncher()
  File "/usr/local/bin/mylaunchpad", line 650, in __init__
    self.init_window()
  File "/usr/local/bin/mylaunchpad", line 772, in init_window
    buf = StringIO.StringIO()
NameError: global name 'StringIO' is not defined

any idea? :D thx for all!

**Comment by x11tete11x** [comment]
i was cause i was trought a vnc session, works flawessly! thx!

**Comment by x11tete11x** [comment]
*it was cause i was trought a vnc session, works flawessly! thx!
